use readerdb; 

insert into books (book_id, isbn, title, author, purchase_link, price, average_rating, description) values (1, '809787790-2', 'Open-architected optimal flexibility', 'Poppy Delleschi', 'https://prlog.org/vitae/quam/suspendisse/potenti.jsp?turpis=ultrices&nec=mattis&euismod=odio&scelerisque=donec&quam=vitae&turpis=nisi&adipiscing=nam&lorem=ultrices&vitae=libero&mattis=non&nibh=mattis&ligula=pulvinar&nec=nulla&sem=pede&duis=ullamcorper&aliquam=augue&convallis=a&nunc=suscipit&proin=nulla&at=elit&turpis=ac&a=nulla&pede=sed&posuere=vel&nonummy=enim&integer=sit&non=amet&velit=nunc&donec=viverra&diam=dapibus&neque=nulla&vestibulum=suscipit&eget=ligula&vulputate=in&ut=lacus&ultrices=curabitur&vel=at&augue=ipsum&vestibulum=ac&ante=tellus&ipsum=semper&primis=interdum&in=mauris&faucibus=ullamcorper&orci=purus&luctus=sit&et=amet&ultrices=nulla&posuere=quisque&cubilia=arcu&curae=libero&donec=rutrum&pharetra=ac&magna=lobortis&vestibulum=vel&aliquet=dapibus&ultrices=at', 27.26, 35, 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis');
insert into books (book_id, isbn, title, author, purchase_link, price, average_rating, description) values (2, '637057750-2', 'Operative contextually-based initiative', 'Sherm Winney', 'https://statcounter.com/rhoncus/sed/vestibulum/sit.json?turpis=suscipit&adipiscing=a&lorem=feugiat&vitae=et&mattis=eros&nibh=vestibulum&ligula=ac&nec=est&sem=lacinia&duis=nisi&aliquam=venenatis&convallis=tristique&nunc=fusce&proin=congue&at=diam&turpis=id&a=ornare&pede=imperdiet&posuere=sapien&nonummy=urna&integer=pretium&non=nisl&velit=ut&donec=volutpat&diam=sapien&neque=arcu&vestibulum=sed&eget=augue&vulputate=aliquam&ut=erat&ultrices=volutpat&vel=in&augue=congue&vestibulum=etiam&ante=justo&ipsum=etiam&primis=pretium&in=iaculis&faucibus=justo&orci=in&luctus=hac&et=habitasse&ultrices=platea&posuere=dictumst&cubilia=etiam&curae=faucibus&donec=cursus&pharetra=urna&magna=ut&vestibulum=tellus&aliquet=nulla&ultrices=ut&erat=erat&tortor=id&sollicitudin=mauris&mi=vulputate&sit=elementum&amet=nullam&lobortis=varius&sapien=nulla&sapien=facilisi&non=cras&mi=non&integer=velit&ac=nec&neque=nisi&duis=vulputate&bibendum=nonummy&morbi=maecenas&non=tincidunt', 34.78, 78, 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper');
insert into books (book_id, isbn, title, author, purchase_link, price, average_rating, description) values (3, '723471569-X', 'Assimilated systemic monitoring', 'Iggy Franckton', 'http://pbs.org/lectus/suspendisse.json?maecenas=lorem&ut=vitae&massa=mattis&quis=nibh&augue=ligula&luctus=nec&tincidunt=sem&nulla=duis&mollis=aliquam&molestie=convallis&lorem=nunc&quisque=proin&ut=at&erat=turpis&curabitur=a&gravida=pede&nisi=posuere&at=nonummy&nibh=integer&in=non&hac=velit&habitasse=donec&platea=diam&dictumst=neque&aliquam=vestibulum&augue=eget&quam=vulputate&sollicitudin=ut&vitae=ultrices&consectetuer=vel&eget=augue&rutrum=vestibulum&at=ante&lorem=ipsum&integer=primis&tincidunt=in&ante=faucibus&vel=orci&ipsum=luctus&praesent=et&blandit=ultrices&lacinia=posuere&erat=cubilia&vestibulum=curae&sed=donec&magna=pharetra&at=magna&nunc=vestibulum&commodo=aliquet&placerat=ultrices&praesent=erat&blandit=tortor&nam=sollicitudin&nulla=mi&integer=sit&pede=amet&justo=lobortis&lacinia=sapien&eget=sapien&tincidunt=non&eget=mi&tempus=integer&vel=ac&pede=neque&morbi=duis&porttitor=bibendum&lorem=morbi&id=non&ligula=quam&suspendisse=nec&ornare=dui&consequat=luctus&lectus=rutrum&in=nulla&est=tellus&risus=in&auctor=sagittis&sed=dui&tristique=vel&in=nisl&tempus=duis', 32.69, 33, 'ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus');
insert into books (book_id, isbn, title, author, purchase_link, price, average_rating, description) values (4, '957313478-0', 'Reactive intermediate paradigm', 'Vina Jerrand', 'https://pen.io/vulputate.xml?lacinia=vitae&nisi=nisl&venenatis=aenean&tristique=lectus&fusce=pellentesque&congue=eget&diam=nunc&id=donec&ornare=quis&imperdiet=orci&sapien=eget&urna=orci&pretium=vehicula&nisl=condimentum&ut=curabitur&volutpat=in&sapien=libero&arcu=ut&sed=massa&augue=volutpat&aliquam=convallis&erat=morbi&volutpat=odio&in=odio&congue=elementum&etiam=eu&justo=interdum&etiam=eu&pretium=tincidunt&iaculis=in&justo=leo&in=maecenas&hac=pulvinar&habitasse=lobortis&platea=est&dictumst=phasellus&etiam=sit&faucibus=amet&cursus=erat&urna=nulla&ut=tempus&tellus=vivamus&nulla=in&ut=felis', 31.6, 55, 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique');
insert into books (book_id, isbn, title, author, purchase_link, price, average_rating, description) values (5, '209174430-1', 'Implemented multimedia algorithm', 'Aron Lanfer', 'http://google.com.hk/pellentesque/eget/nunc.jpg?mattis=nisl&nibh=venenatis&ligula=lacinia&nec=aenean&sem=sit&duis=amet&aliquam=justo&convallis=morbi&nunc=ut&proin=odio&at=cras&turpis=mi&a=pede&pede=malesuada&posuere=in&nonummy=imperdiet&integer=et&non=commodo&velit=vulputate&donec=justo&diam=in&neque=blandit&vestibulum=ultrices&eget=enim&vulputate=lorem&ut=ipsum&ultrices=dolor&vel=sit&augue=amet&vestibulum=consectetuer&ante=adipiscing&ipsum=elit&primis=proin&in=interdum&faucibus=mauris&orci=non&luctus=ligula&et=pellentesque&ultrices=ultrices&posuere=phasellus&cubilia=id&curae=sapien&donec=in&pharetra=sapien&magna=iaculis&vestibulum=congue&aliquet=vivamus&ultrices=metus&erat=arcu&tortor=adipiscing&sollicitudin=molestie&mi=hendrerit&sit=at&amet=vulputate&lobortis=vitae&sapien=nisl&sapien=aenean&non=lectus&mi=pellentesque&integer=eget&ac=nunc&neque=donec&duis=quis&bibendum=orci&morbi=eget&non=orci&quam=vehicula&nec=condimentum&dui=curabitur&luctus=in&rutrum=libero&nulla=ut&tellus=massa&in=volutpat&sagittis=convallis&dui=morbi&vel=odio&nisl=odio&duis=elementum&ac=eu&nibh=interdum&fusce=eu&lacus=tincidunt&purus=in&aliquet=leo&at=maecenas', 46.23, 67, 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl');
insert into books (book_id, isbn, title, author, purchase_link, price, average_rating, description) values (6, '567214425-X', 'Versatile transitional collaboration', 'Carmelle Tosney', 'http://posterous.com/natoque/penatibus/et/magnis/dis.xml?condimentum=porttitor&curabitur=lacus&in=at&libero=turpis&ut=donec&massa=posuere&volutpat=metus&convallis=vitae&morbi=ipsum&odio=aliquam&odio=non&elementum=mauris&eu=morbi&interdum=non&eu=lectus&tincidunt=aliquam&in=sit&leo=amet&maecenas=diam&pulvinar=in', 36.79, 28, 'sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris');
insert into books (book_id, isbn, title, author, purchase_link, price, average_rating, description) values (7, '689716534-4', 'Streamlined real-time help-desk', 'Dulce Adolf', 'http://hexun.com/venenatis/tristique/fusce/congue/diam/id.json?accumsan=ultrices&tortor=erat&quis=tortor&turpis=sollicitudin&sed=mi&ante=sit&vivamus=amet&tortor=lobortis&duis=sapien&mattis=sapien&egestas=non&metus=mi&aenean=integer&fermentum=ac&donec=neque&ut=duis&mauris=bibendum&eget=morbi&massa=non&tempor=quam&convallis=nec&nulla=dui&neque=luctus&libero=rutrum&convallis=nulla&eget=tellus&eleifend=in&luctus=sagittis&ultricies=dui&eu=vel&nibh=nisl&quisque=duis&id=ac&justo=nibh&sit=fusce&amet=lacus&sapien=purus&dignissim=aliquet&vestibulum=at', 9.95, 40, 'sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum');
insert into books (book_id, isbn, title, author, purchase_link, price, average_rating, description) values (8, '471647917-X', 'Object-based modular flexibility', 'Carole Bernardes', 'https://a8.net/sagittis/sapien/cum/sociis/natoque/penatibus/et.png?nullam=vulputate&porttitor=justo&lacus=in&at=blandit&turpis=ultrices&donec=enim&posuere=lorem&metus=ipsum&vitae=dolor&ipsum=sit&aliquam=amet&non=consectetuer&mauris=adipiscing&morbi=elit&non=proin&lectus=interdum&aliquam=mauris&sit=non&amet=ligula&diam=pellentesque&in=ultrices&magna=phasellus&bibendum=id&imperdiet=sapien&nullam=in&orci=sapien&pede=iaculis&venenatis=congue&non=vivamus&sodales=metus&sed=arcu&tincidunt=adipiscing&eu=molestie&felis=hendrerit&fusce=at&posuere=vulputate&felis=vitae&sed=nisl&lacus=aenean&morbi=lectus&sem=pellentesque&mauris=eget&laoreet=nunc&ut=donec&rhoncus=quis&aliquet=orci&pulvinar=eget&sed=orci&nisl=vehicula&nunc=condimentum&rhoncus=curabitur&dui=in&vel=libero&sem=ut&sed=massa&sagittis=volutpat&nam=convallis&congue=morbi&risus=odio', 12.09, 17, 'sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam');
insert into books (book_id, isbn, title, author, purchase_link, price, average_rating, description) values (9, '926104593-6', 'Multi-tiered zero defect secured line', 'Britteny Maddrell', 'http://harvard.edu/amet/erat/nulla/tempus.xml?purus=risus&aliquet=auctor&at=sed&feugiat=tristique&non=in&pretium=tempus&quis=sit&lectus=amet&suspendisse=sem&potenti=fusce&in=consequat&eleifend=nulla&quam=nisl&a=nunc&odio=nisl&in=duis&hac=bibendum&habitasse=felis&platea=sed&dictumst=interdum&maecenas=venenatis&ut=turpis&massa=enim&quis=blandit&augue=mi&luctus=in&tincidunt=porttitor&nulla=pede&mollis=justo&molestie=eu&lorem=massa&quisque=donec&ut=dapibus&erat=duis&curabitur=at&gravida=velit&nisi=eu&at=est&nibh=congue&in=elementum&hac=in&habitasse=hac&platea=habitasse&dictumst=platea&aliquam=dictumst&augue=morbi&quam=vestibulum&sollicitudin=velit&vitae=id&consectetuer=pretium&eget=iaculis&rutrum=diam&at=erat&lorem=fermentum&integer=justo&tincidunt=nec&ante=condimentum&vel=neque&ipsum=sapien&praesent=placerat&blandit=ante&lacinia=nulla&erat=justo&vestibulum=aliquam&sed=quis&magna=turpis&at=eget&nunc=elit&commodo=sodales&placerat=scelerisque&praesent=mauris&blandit=sit&nam=amet&nulla=eros&integer=suspendisse&pede=accumsan&justo=tortor&lacinia=quis&eget=turpis&tincidunt=sed&eget=ante&tempus=vivamus&vel=tortor&pede=duis&morbi=mattis&porttitor=egestas&lorem=metus', 2.59, 32, 'turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit');
insert into books (book_id, isbn, title, author, purchase_link, price, average_rating, description) values (10, '175592093-8', 'Down-sized uniform forecast', 'Gill Millership', 'https://mozilla.org/cum/sociis/natoque/penatibus/et/magnis.js?at=ante&dolor=ipsum&quis=primis&odio=in&consequat=faucibus&varius=orci&integer=luctus&ac=et&leo=ultrices&pellentesque=posuere&ultrices=cubilia&mattis=curae&odio=duis&donec=faucibus&vitae=accumsan&nisi=odio&nam=curabitur&ultrices=convallis&libero=duis&non=consequat&mattis=dui&pulvinar=nec&nulla=nisi&pede=volutpat&ullamcorper=eleifend&augue=donec&a=ut&suscipit=dolor&nulla=morbi&elit=vel&ac=lectus&nulla=in&sed=quam&vel=fringilla&enim=rhoncus&sit=mauris&amet=enim', 24.5, 75, 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat');


insert into users (user_id, username, password, email) values (1, 'cpurdy0', 'QB4gQFp4', 'mbeldon0@histats.com');
insert into users (user_id, username, password, email) values (2, 'bstonnell1', '56v76TJ', 'vdaffern1@cocolog-nifty.com');
insert into users (user_id, username, password, email) values (3, 'lpollicote2', 'qnSVzvKLfDs', 'fboodell2@simplemachines.org');
insert into users (user_id, username, password, email) values (4, 'khardern3', '3gWo8b', 'aferrick3@epa.gov');
insert into users (user_id, username, password, email) values (5, 'aberends4', 'ij2oiW9u8', 'dbillam4@admin.ch');
insert into users (user_id, username, password, email) values (6, 'manstiss5', 'MfbjqIIk6a', 'bpleat5@theglobeandmail.com');
insert into users (user_id, username, password, email) values (7, 'njachimak6', 'MOv2Fl', 'smenichino6@stumbleupon.com');
insert into users (user_id, username, password, email) values (8, 'dgingle7', 'AWEnfLbsJ', 'slago7@nature.com');
insert into users (user_id, username, password, email) values (9, 'lnewick8', 'sv3a6qQG', 'svanarsdall8@unblog.fr');
insert into users (user_id, username, password, email) values (10, 'mcail9', '76QscYjXdZrm', 'hdrable9@myspace.com');

INSERT INTO bookUserJoin (user_id, book_id) VALUES (1, 5); 

-- example join  

-- SELECT * FROM bookUserJoin
-- LEFT JOIN books 
-- ON bookUserJoin.book_id = books.book_id
-- LEFT JOIN users
-- ON bookUserJoin.user_id = users.user_id;